// ********RoostGPT********
/*
Test generated by RoostGPT for test grpc-unit-new using AI Type Azure Open AI and AI Model roostgpt-4-32k

Test generated by RoostGPT for test grpc-unit-new using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=ArticleStore_Create_1273475ade
ROOST_METHOD_SIG_HASH=ArticleStore_Create_a27282cad5

FUNCTION_DEF=func (s *ArticleStore) Create(m *model.Article) error // Create creates an article

Scenario 1: Successful Article Creation

  Details:
    Description: This test is meant to check that an article can be successfully created and stored in the database. The target scenario is a standard usage case where all data provided is correct and valid.

  Execution:
    Arrange: A valid instance of model.Article and a mock instance of *gorm.DB (where the Create method succeeds without error) has to be set.
    Act: Invoke the function Create() with the mock gorm.DB and the new article.
    Assert: Verify that the Create() method was called with the correct article, and that the return value of the functions is nil (indicating success).

  Validation:
    The assertions are chosen to verify both the interaction with the gorm.DB object and the overall result of the operation. The test is important to ensure that new articles can be correctly and reliably stored in the system.

Scenario 2: Database Creation Error

  Details:
    Description: This test is meant to check that an error from the database layer is correctly propagated up the call stack. The target scenario is an edge case where something goes wrong in the database.

  Execution:
    Arrange: An instance of model.Article and a mock instance of *gorm.DB (where the Create method returns an error) should be prepared.
    Act: Invoke the function Create() with the mock gorm.DB and the new article.
    Assert: Verify that the return value of the function equals the error returned from the mock db.

  Validation:
    The assertions are chosen to ensure that errors are suitably handled and returned to allow for appropriate error handling up the stack. This is important as it provides information on what went wrong, which can be helpful for debugging and potentially for user feedback.

Scenario 3: Nil Article Provided

  Details:
    Description: This test is meant to check that an error is returned when a nil article is given. The target scenario is an edge case where incorrect data is provided.

  Execution:
    Arrange: Prepare a mock instance of *gorm.DB.
    Act: Invoke the function Create() with the mock gorm.DB and a nil article.
    Assert: Verify that the function returns a non-nil error value.

  Validation:
    The assertion verifies that the function generates an error when given inappropriate inputs. This is important to avoid a potential panic and to provide feedback about incorrect usage to other components or services using the function.
*/

// ********RoostGPT********

package store

import (
	"errors"
	"runtime/debug"
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
)

func TestArticleStoreCreate(t *testing.T) {
	db, mock, err := sqlmock.New(sqlmock.QueryMatcherOption(sqlmock.QueryMatcherEqual))
	if err != nil {
		t.Fatalf("Expected no error, but got: %v", err)
	}
	gormDB, _ := gorm.Open("postgres", db)

	fakeArticle := &model.Article{
		ID:          1,
		Title:       "How to train your dragon",
		Slug:        "how-to-train-your-dragon",
		Description: "Ever wonder how?",
		Body:        "You have to believe",
		Author:      model.Profile{Username: "johndoe", Bio: "I work at statefarm", Image: "image.jpg", Following: false},
	}

	tests := []struct {
		name  string
		input *model.Article
		err   error
	}{
		{name: "Successful Article Creation", input: fakeArticle, err: nil},
		{name: "Database Creation Error", input: fakeArticle, err: gorm.ErrRecordNotFound},
		{name: "Nil Article Provided", input: nil, err: gorm.ErrInvalidSQL},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v\n%s", r, string(debug.Stack()))
					t.Fail()
				}
			}()

			articleStore := &ArticleStore{db: gormDB}

			mock.ExpectBegin()

			mock.ExpectExec("^ INSERT INTO \"articles\" (.+) VALUES (.+) $").
				WithArgs(fakeArticle.ID, fakeArticle.Title, fakeArticle.Slug, fakeArticle.Description, fakeArticle.Body, fakeArticle.Author).
				WillReturnResult(sqlmock.NewResult(1, 1))

			mock.ExpectCommit()

			err := articleStore.Create(tt.input)

			if err != nil {
				if !errors.Is(err, tt.err) {
					t.Errorf("Expected error %v, but got: %v", tt.err, err)
				}
			} else {
				if tt.err != nil {
					t.Errorf("Expected no error, but got: %v", err)
				}
			}
		})
	}
}
