// ********RoostGPT********
/*
Test generated by RoostGPT for test golang-1 using AI Type Azure Open AI and AI Model roostgpt-4-32k

ROOST_METHOD_HASH=NewArticleStore_85784abca5
ROOST_METHOD_SIG_HASH=NewArticleStore_436ae9c986

FUNCTION_DEF=func NewArticleStore(db *gorm.DB) *ArticleStore // NewArticleStore returns a new ArticleStore

Scenario 1: NewArticleStore With Valid DataBase Instance

Details:
Description: This test ensures that the function can properly create and return a new ArticleStore instance when provided with a valid *gorm.DB instance.
Execution:
Arrange: Create a valid *gorm.DB instance.
Act: Call NewArticleStore function with the *gorm.DB instance as a parameter.
Assert: Assert that the returned *ArticleStore instance is not nil and that its internal `db` field matches the *gorm.DB instance provided in the `Arrange` step.
Validation:
The assertion confirms that the `NewArticleStore` is operating as expected in normal conditions. This is crucial, as the function should be capable of generating an `ArticleStore` instance when supplied with a valid `*gorm.DB` object.

Scenario 2: NewArticleStore With Nil DataBase Instance

Details:
Description: This test makes sure that the function can correctly handle and return a new ArticleStore instance when provided with a nil for the *gorm.DB.
Execution:
Arrange: Set the *gorm.DB instance to nil.
Act: Invoke NewArticleStore function with the nil *gorm.DB instance as a parameter.
Assert: Assert that the returned *ArticleStore instance is not nil and that its internal `db` field is also nil.
Validation:
The assertion makes sure that the `NewArticleStore` can manage `nil` input without failing, and it still returns an `ArticleStore` instance, albeit one that might not be usable due to the `nil` `db` field. It's crucial in order to check the function's resilience and error handling.

roost_feedback [2/13/2025, 11:24:00 AM]:Modify Code to fix this error\n./article_newarticlestore_test.go:50:9: cannot use mdb (variable of type *mockDB) as *gorm.DB value in return statement\n\nUse a  return &gorm.DB{} instead of the existing code

roost_feedback [2/13/2025, 2:41:58 PM]:Modify Code to fix this error\n./article_newarticlestore_test.go:50:9: cannot use mdb (variable of type *mockDB) as *gorm.DB value in return statement\n\nYou can use this kind of a setup function\n```\nfunc setupMockDB() *gorm.DB {\n\tsqlDB, _, _ := sqlmock.New()\n\tdb, _ := gorm.Open(postgres, sqlDB)\n\treturn db\n}\n\n```
*/

// ********RoostGPT********

package store

import (
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/stretchr/testify/assert"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
)

func TestNewArticleStore(t *testing.T) {
	var tests = []struct {
		name     string
		db       *gorm.DB
		expected *ArticleStore
	}{
		{
			name:     "Test with valid DB Instance",
			db:       setupMockDB(),
			expected: &ArticleStore{db: setupMockDB()},
		},
		{
			name:     "Test with nil DB Instance",
			db:       nil,
			expected: &ArticleStore{db: nil},
		},
	}

	for _, tc := range tests {

		t.Run(tc.name, func(t *testing.T) {
			actual := NewArticleStore(tc.db)
			assert.NotNil(t, actual, "ArticleStore should not be nil")
			assert.Equal(t, tc.expected.db, actual.db, "Expected and Actual DB should match")
		})
	}
}

// setupMockDB creates a mock DB for testing
func setupMockDB() *gorm.DB {
	sqlDB, _, _ := sqlmock.New()
	dialector := postgres.New(postgres.Config{Conn: sqlDB})
	db, _ := gorm.Open(dialector, &gorm.Config{})
	return db
}
