// ********RoostGPT********
/*
Test generated by RoostGPT for test golang-grpc-2 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test golang-grpc-2 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=NewArticleStore_85784abca5
ROOST_METHOD_SIG_HASH=NewArticleStore_436ae9c986

FUNCTION_DEF=func NewArticleStore(db *gorm.DB) *ArticleStore // NewArticleStore returns a new ArticleStore

Scenario 1: Successful creation of a new ArticleStore

Details:
  Description: This test is meant to check if the NewArticleStore function can successfully create a new ArticleStore instance with a provided database connection.
Execution:
  Arrange: Mock a gorm.DB instance.
  Act: Invoke NewArticleStore with the mock DB instance.
  Assert: Use Go testing facilities to verify that the returned ArticleStore is not nil and its db field is the same as the mock DB instance.
Validation:
  The assertion checks if the function correctly initializes a new ArticleStore with the provided DB instance. This test is important to ensure that the function can correctly set up the database connection for the ArticleStore.

Scenario 2: Creation of a new ArticleStore with a nil DB

Details:
  Description: This test is meant to check if the NewArticleStore function can handle a nil DB instance.
Execution:
  Arrange: No setup is required as we are passing nil as the DB instance.
  Act: Invoke NewArticleStore with nil as the DB instance.
  Assert: Use Go testing facilities to verify that the returned ArticleStore is not nil and its db field is nil.
Validation:
  The assertion checks if the function correctly initializes a new ArticleStore even when the DB instance is nil. This test is important to ensure that the function can handle edge cases and does not crash when provided with nil inputs.

Scenario 3: Multiple invocations of NewArticleStore

Details:
  Description: This test is meant to check if the NewArticleStore function can handle multiple invocations and create separate ArticleStore instances.
Execution:
  Arrange: Mock two different gorm.DB instances.
  Act: Invoke NewArticleStore twice with the two different mock DB instances.
  Assert: Use Go testing facilities to verify that the returned ArticleStores are not nil, their db fields are the same as the respective mock DB instances, and the two ArticleStores are not the same instance.
Validation:
  The assertion checks if the function correctly creates separate ArticleStore instances for each invocation. This test is important to ensure that the function does not reuse instances and correctly initializes each new ArticleStore.
*/

// ********RoostGPT********

package store

import (
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/stretchr/testify/assert"
)

func TestNewArticleStore(t *testing.T) {

	testCases := []struct {
		name     string
		db       *gorm.DB
		expected *ArticleStore
	}{
		{
			name:     "Successful creation of a new ArticleStore",
			db:       newMockDB(),
			expected: &ArticleStore{db: newMockDB()},
		},
		{
			name:     "Creation of a new ArticleStore with a nil DB",
			db:       nil,
			expected: &ArticleStore{db: nil},
		},
		{
			name:     "Multiple invocations of NewArticleStore",
			db:       newMockDB(),
			expected: &ArticleStore{db: newMockDB()},
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			result := NewArticleStore(tc.db)

			assert.NotNil(t, result)
			assert.Equal(t, tc.expected.db, result.db)
		})
	}
}
func newMockDB() *gorm.DB {
	db, _, _ := sqlmock.New()
	gormDB, _ := gorm.Open("postgres", db)
	return gormDB
}
