// ********RoostGPT********
/*
Test generated by RoostGPT for test golang-grpc-2 using AI Type Open AI and AI Model gpt-4

Test generated by RoostGPT for test golang-grpc-2 using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=ArticleStore_GetByID_6fe18728fc
ROOST_METHOD_SIG_HASH=ArticleStore_GetByID_bb488e542f

FUNCTION_DEF=func (s *ArticleStore) GetByID(id uint) (*model.Article, error) // GetByID finds an article from id

Scenario 1: Successful retrieval of an article by ID

Details:
  Description: This test is meant to check if the function correctly retrieves an article from the database when provided with a valid ID. The article should be preloaded with its associated tags and author.

Execution:
  Arrange: Mock the database to return a specific article when queried with a given ID. The article should have associated tags and an author.
  Act: Invoke the GetByID function with the ID of the mocked article.
  Assert: Use Go testing facilities to verify that the returned article matches the mocked article and that no error is returned.

Validation:
  The assertion checks that the function correctly retrieves and returns the article from the database. This test is important as it verifies the function's primary functionality under normal operation.

Scenario 2: Attempt to retrieve an article with a non-existent ID

Details:
  Description: This test is meant to check if the function correctly handles a scenario where it is asked to retrieve an article with an ID that does not exist in the database.

Execution:
  Arrange: Mock the database to return an error when queried with a non-existent ID.
  Act: Invoke the GetByID function with a non-existent ID.
  Assert: Use Go testing facilities to verify that the function returns an error.

Validation:
  The assertion checks that the function correctly handles an error from the database. This test is important as it verifies the function's error handling capabilities when asked to retrieve a non-existent article.

Scenario 3: Database error during retrieval of an article

Details:
  Description: This test is meant to check if the function correctly handles a scenario where a database error occurs during the retrieval of an article.

Execution:
  Arrange: Mock the database to return an error when queried with a valid ID.
  Act: Invoke the GetByID function with a valid ID.
  Assert: Use Go testing facilities to verify that the function returns an error.

Validation:
  The assertion checks that the function correctly handles a database error. This test is important as it verifies the function's error handling capabilities when a database error occurs during the retrieval of an article.
*/

// ********RoostGPT********

package store

import (
	"errors"
	"testing"

	"github.com/DATA-DOG/go-sqlmock"
	"github.com/jinzhu/gorm"
	"github.com/raahii/golang-grpc-realworld-example/model"
	"github.com/stretchr/testify/assert"
)

func TestArticleStoreGetById(t *testing.T) {

	testCases := []struct {
		name            string
		articleID       uint
		mockBehaviour   func(mock sqlmock.Sqlmock, id uint)
		expectedArticle *model.Article
		expectedError   error
	}{
		{
			name:      "Successful retrieval of an article by ID",
			articleID: 1,
			mockBehaviour: func(mock sqlmock.Sqlmock, id uint) {
				rows := sqlmock.NewRows([]string{"id", "title", "description", "body", "user_id"}).
					AddRow(id, "Test Title", "Test Description", "Test Body", 1)
				mock.ExpectQuery("SELECT").WithArgs(id).WillReturnRows(rows)
			},
			expectedArticle: &model.Article{
				Model:       gorm.Model{ID: 1},
				Title:       "Test Title",
				Description: "Test Description",
				Body:        "Test Body",
				UserID:      1,
			},
			expectedError: nil,
		},
		{
			name:      "Attempt to retrieve an article with a non-existent ID",
			articleID: 2,
			mockBehaviour: func(mock sqlmock.Sqlmock, id uint) {
				mock.ExpectQuery("SELECT").WithArgs(id).WillReturnError(gorm.ErrRecordNotFound)
			},
			expectedArticle: nil,
			expectedError:   gorm.ErrRecordNotFound,
		},
		{
			name:      "Database error during retrieval of an article",
			articleID: 3,
			mockBehaviour: func(mock sqlmock.Sqlmock, id uint) {
				mock.ExpectQuery("SELECT").WithArgs(id).WillReturnError(errors.New("database error"))
			},
			expectedArticle: nil,
			expectedError:   errors.New("database error"),
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {

			defer func() {
				if r := recover(); r != nil {
					t.Logf("Panic encountered so failing test. %v", r)
					t.Fail()
				}
			}()

			db, mock, err := sqlmock.New()
			if err != nil {
				t.Fatalf("failed to open sqlmock database: %v", err)
			}
			defer db.Close()

			gdb, err := gorm.Open("postgres", db)
			if err != nil {
				t.Fatalf("failed to open gorm database: %v", err)
			}

			tc.mockBehaviour(mock, tc.articleID)

			store := &ArticleStore{db: gdb}

			article, err := store.GetByID(tc.articleID)

			assert.Equal(t, tc.expectedArticle, article)
			assert.Equal(t, tc.expectedError, err)
		})
	}
}
